# Generated by Django 5.2.4 on 2025-10-24 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_app', '0004_project_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='investor_app.project'),
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('areas_of_interest', models.TextField(blank=True, help_text='Comma-separated list of interests (e.g., AI, FinTech, Healthcare)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
