# Generated by Django 5.2.4 on 2025-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor_app', '0005_alter_chatmessage_project_investorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_woman_led',
            field=models.BooleanField(default=False),
        ),
    ]
